name: Go

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
        id: go

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          hash=$(git rev-list --tags --max-count=1)
          version=$(git describe --tags $hash)
          flag="-s -w -X main.version=$version"
          go mod tidy
          GOOS=windows GOARCH=amd64 go build -ldflags "$flag" -o build/windows-amd64/jvms.exe
          GOOS=windows GOARCH=386   go build -ldflags "$flag" -o build/windows-386/jvms.exe

      - name: Create ZIP archives
        run: |
          hash=$(git rev-list --tags --max-count=1)
          version=$(git describe --tags $hash)
          zip -j jvms_${version}_amd64.zip build/windows-amd64/jvms.exe
          zip -j jvms_${version}_386.zip   build/windows-386/jvms.exe

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jvms_*_amd64.zip
            jvms_*_386.zip
